import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../prisma/prisma.service';
import { HmacService } from '../common/security/hmac.service';
import { RegisterAppDto, UpdateAppDto } from './dto/register-app.dto';

@Injectable()
export class WebhooksService {
  private readonly logger = new Logger(WebhooksService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly configService: ConfigService,
    private readonly hmac: HmacService,
  ) {}

  // ─── Registered App CRUD ──────────────────────────────────────────────────

  async registerApp(dto: RegisterAppDto) {
    const app = await this.prisma.registeredApp.create({
      data: {
        name: dto.name,
        webhookUrl: dto.webhookUrl,
        // webhookSecret auto-generated by Prisma default (cuid)
      },
    });
    this.logger.log(`[Webhook] Registered app: ${app.name} (id: ${app.id})`);

    return {
      id:            app.id,
      name:          app.name,
      webhookUrl:    app.webhookUrl,
      webhookSecret: app.webhookSecret, // only shown at creation — treat like an API key
      isActive:      app.isActive,
      createdAt:     app.createdAt,
      _note: 'Save webhookSecret — it will not be shown again in plain text.',
    };
  }

  async listApps() {
    return this.prisma.registeredApp.findMany({
      orderBy: { createdAt: 'desc' },
      select: {
        id: true, name: true, webhookUrl: true,
        isActive: true, createdAt: true, updatedAt: true,
        // intentionally omit webhookSecret from list
      },
    });
  }

  async getApp(id: string) {
    const app = await this.prisma.registeredApp.findUnique({ where: { id } });
    if (!app) throw new NotFoundException(`App ${id} not found`);
    const { webhookSecret, ...rest } = app; // never return secret in GET
    return rest;
  }

  async updateApp(id: string, dto: UpdateAppDto) {
    await this.getApp(id); // existence check
    return this.prisma.registeredApp.update({ where: { id }, data: dto });
  }

  async rotateSecret(id: string) {
    await this.getApp(id);
    const app = await this.prisma.registeredApp.update({
      where: { id },
      data: { webhookSecret: require('crypto').randomUUID() },
    });
    return { id: app.id, webhookSecret: app.webhookSecret, rotatedAt: new Date() };
  }

  async deleteApp(id: string) {
    await this.getApp(id);
    await this.prisma.registeredApp.delete({ where: { id } });
    return { message: `App ${id} deleted` };
  }

  // ─── Inbound webhook handlers (from eSewa / Khalti) ───────────────────────

  verifySignature(payload: string, signature: string): boolean {
    const secret = this.configService.get<string>('WEBHOOK_SECRET', 'fallback');
    return this.hmac.verifyWithSecret(payload, signature, secret);
  }

  async handleEsewaWebhook(payload: any) {
    this.logger.log(`[Webhook] eSewa inbound: ${JSON.stringify(payload)}`);
    await this.prisma.webhookEvent.create({
      data: { provider: 'ESEWA', eventType: payload.event ?? 'unknown', payload, processed: false },
    });
    if (payload.status === 'SUCCESS') {
      await this.prisma.transaction.updateMany({
        where: { externalId: payload.transactionId },
        data: { status: 'COMPLETED', completedAt: new Date() },
      });
    }
    await this.prisma.webhookEvent.updateMany({
      where: { provider: 'ESEWA', processed: false },
      data: { processed: true },
    });
    return { received: true };
  }

  async handleKhaltiWebhook(payload: any) {
    this.logger.log(`[Webhook] Khalti inbound: ${JSON.stringify(payload)}`);
    await this.prisma.webhookEvent.create({
      data: { provider: 'KHALTI', eventType: payload.event ?? 'unknown', payload, processed: false },
    });
    if (payload.status === 'Completed') {
      await this.prisma.transaction.updateMany({
        where: { externalId: payload.idx },
        data: { status: 'COMPLETED', completedAt: new Date() },
      });
    }
    return { received: true };
  }
}
